services:
  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
  redis:
    ports:
      - "127.0.0.1:6379:6379"
  rabbitmq:
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
  minio:
    image: telegramlocal/minio:RELEASE.2025-10-15T17-29-55Z
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:9000/minio/health/live"]
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
